export const BUSINESS_RULES_CONFIG = {
  DEFAULT_MAINTENANCE_INTERVAL_HOURS: 250,
  MIN_SHIFT_DURATION_HOURS: 1,
  MAX_SHIFT_DURATION_HOURS: 24,
  DEFAULT_SHIFT_DURATION_HOURS: 8,
  MIN_SUPERVISOR_OVERRIDE_REASON_LENGTH: 10,
  PROJECTION_HORIZON_DAYS: 7,
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
} as const;
